import type { Metadata } from "next";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import { SITE } from "@/lib/constants";

export const metadata: Metadata = {
  title: "Case Study: SellerPilotAI | IntellectAI",
  description:
    "How IntellectAI built SellerPilotAI, an AI-powered compliance monitoring SaaS for Amazon sellers. From concept to launch in under 4 weeks.",
  openGraph: {
    title: "Case Study: SellerPilotAI | IntellectAI",
    description:
      "AI-powered compliance monitoring for Amazon sellers. Built in under 4 weeks.",
  },
};

const TIMELINE = [
  {
    week: "Week 1",
    title: "Research & Architecture",
    items: [
      "Deep research into Amazon compliance and seller pain points",
      "Designed AI agent architecture for compliance monitoring",
      "Database schema and API architecture design",
    ],
  },
  {
    week: "Week 2",
    title: "Core Development",
    items: [
      "Built compliance monitoring engine using Claude API",
      "Developed seller dashboard with real-time visualization",
      "Created alert and notification system",
    ],
  },
  {
    week: "Week 3",
    title: "AI Agent Integration",
    items: [
      "Trained and deployed specialized compliance agents",
      "Built recommendation engine for actionable fix-it guides",
      "Integrated with Amazon seller data feeds",
    ],
  },
  {
    week: "Week 4",
    title: "Testing & Launch",
    items: [
      "Beta testing with Amazon sellers",
      "Performance optimization and stress testing",
      "Public launch at sellerpilotai.ai",
    ],
  },
];

const STATS = [
  { value: "< 4 Weeks", label: "Concept to Launch" },
  { value: "24/7", label: "Continuous Monitoring" },
  { value: "$49/mo", label: "Starting Price" },
  { value: "$3,000+", label: "Monthly VA Cost Replaced" },
];

const TECH_STACK = [
  { category: "Frontend", tech: "Next.js 14+, React, Tailwind CSS, TypeScript" },
  { category: "Backend", tech: "Node.js, Python (FastAPI) for AI processing" },
  { category: "Database", tech: "Supabase (PostgreSQL) with real-time subscriptions" },
  { category: "AI Engine", tech: "Claude API (Anthropic) for agentic reasoning" },
  { category: "Automations", tech: "n8n / Make.com for workflow orchestration" },
  { category: "Hosting", tech: "Vercel (frontend) + AWS (backend services)" },
];

const FEATURES = [
  {
    title: "Real-Time Compliance Monitoring",
    description:
      "AI agents continuously scan for policy violations, listing suppressions, and account health risks. Catching issues before Amazon does.",
  },
  {
    title: "Account Health Dashboard",
    description:
      "Single view of your account health score, active alerts, risk trends, and compliance status across all listings.",
  },
  {
    title: "Proactive Alert System",
    description:
      "Get notified about compliance risks before they become suspensions. No more discovering problems when sales have already dropped.",
  },
  {
    title: "AI-Powered Recommendations",
    description:
      "Step-by-step guidance on how to fix each issue, generated by AI that understands Amazon's policies and your specific situation.",
  },
  {
    title: "Listing Optimization Insights",
    description:
      "Identifies underperforming listings caused by compliance issues and suggests specific improvements to restore performance.",
  },
];

export default function CaseStudyPage() {
  return (
    <>
      <Header />
      <main>
        {/* Hero */}
        <section className="pb-16 pt-32 md:pb-24 md:pt-44" style={{ backgroundColor: "#131416" }}>
          <div className="mx-auto max-w-7xl px-6 md:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <p className="mb-4 text-sm font-semibold uppercase tracking-[0.05em] text-brass-300">
                Case Study
              </p>
              <h1 className="text-[36px] font-extrabold leading-[1.1] tracking-tight text-white md:text-[56px]">
                SellerPilotAI
              </h1>
              <p className="mx-auto mt-4 max-w-2xl text-lg leading-[1.6] text-gray-400 md:text-xl">
                How IntellectAI built a full AI SaaS product from concept to
                launch, proving that agentic AI can replace entire compliance
                teams.
              </p>
              <div className="mt-8 flex flex-wrap items-center justify-center gap-3 text-sm text-gray-400">
                <span className="rounded-full border border-gray-700 px-3 py-1">
                  E-commerce / Amazon
                </span>
                <span className="rounded-full border border-gray-700 px-3 py-1">
                  SaaS Platform
                </span>
                <span className="rounded-full border border-gray-700 px-3 py-1">
                  100% AI-Powered
                </span>
                <span className="rounded-full border border-green-800 bg-green-900/30 px-3 py-1 text-green-400">
                  Live at sellerpilotai.ai
                </span>
              </div>
            </div>
          </div>
        </section>

        {/* Stats Bar */}
        <section className="border-b border-[rgba(255,255,255,0.06)] py-12" style={{ backgroundColor: "#0E0F11" }}>
          <div className="mx-auto grid max-w-5xl grid-cols-2 gap-8 px-6 md:grid-cols-4 md:px-8">
            {STATS.map((stat) => (
              <div key={stat.label} className="text-center">
                <div className="text-2xl font-bold text-brass-300 md:text-3xl">
                  {stat.value}
                </div>
                <div className="mt-1 text-sm text-zinc-400">{stat.label}</div>
              </div>
            ))}
          </div>
        </section>

        {/* The Problem */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#0E0F11" }}>
          <div className="mx-auto max-w-3xl px-6 md:px-8">
            <h2 className="mb-6 text-[28px] font-bold leading-[1.2] tracking-tight text-white md:text-[40px]">
              The Problem
            </h2>
            <p className="mb-6 text-base leading-[1.7] text-zinc-400 md:text-lg">
              Amazon sellers face constant compliance threats that can destroy
              their business overnight:
            </p>
            <ul className="space-y-3 text-base leading-[1.7] text-zinc-400 md:text-lg">
              <li className="flex items-start gap-3">
                <svg
                  className="mt-1.5 h-4 w-4 shrink-0 text-red-500"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <circle cx="12" cy="12" r="10" />
                </svg>
                Account suspensions can take weeks or months to resolve, with
                zero revenue during that time
              </li>
              <li className="flex items-start gap-3">
                <svg
                  className="mt-1.5 h-4 w-4 shrink-0 text-red-500"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <circle cx="12" cy="12" r="10" />
                </svg>
                Listing suppressions happen silently. Sellers don&apos;t realize
                until sales drop
              </li>
              <li className="flex items-start gap-3">
                <svg
                  className="mt-1.5 h-4 w-4 shrink-0 text-red-500"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <circle cx="12" cy="12" r="10" />
                </svg>
                Amazon policy changes frequently without warning
              </li>
              <li className="flex items-start gap-3">
                <svg
                  className="mt-1.5 h-4 w-4 shrink-0 text-red-500"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <circle cx="12" cy="12" r="10" />
                </svg>
                Manual monitoring is expensive. VAs cost $3,000+/month
              </li>
              <li className="flex items-start gap-3">
                <svg
                  className="mt-1.5 h-4 w-4 shrink-0 text-red-500"
                  viewBox="0 0 24 24"
                  fill="currentColor"
                >
                  <circle cx="12" cy="12" r="10" />
                </svg>
                A single compliance failure can wipe out months of profit
              </li>
            </ul>
          </div>
        </section>

        {/* The Solution */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#131416" }}>
          <div className="mx-auto max-w-3xl px-6 md:px-8">
            <h2 className="mb-6 text-[28px] font-bold leading-[1.2] tracking-tight text-white md:text-[40px]">
              The Solution: SellerPilotAI
            </h2>
            <p className="mb-10 text-base leading-[1.7] text-zinc-400 md:text-lg">
              Most Amazon tools are reactive. SellerPilotAI is{" "}
              <strong className="text-white">agentic</strong>. It thinks
              ahead, connects patterns, and takes a proactive stance on
              compliance like an experienced Amazon consultant.
            </p>
            <div className="space-y-6">
              {FEATURES.map((feature) => (
                <div
                  key={feature.title}
                  className="rounded-xl border border-[rgba(255,255,255,0.06)] p-6"
                  style={{ backgroundColor: "#16181B" }}
                >
                  <h3 className="mb-2 text-lg font-bold text-white">
                    {feature.title}
                  </h3>
                  <p className="text-base leading-[1.6] text-zinc-400">
                    {feature.description}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Tech Stack */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#0E0F11" }}>
          <div className="mx-auto max-w-3xl px-6 md:px-8">
            <h2 className="mb-8 text-[28px] font-bold leading-[1.2] tracking-tight text-white md:text-[40px]">
              Tech Stack
            </h2>
            <div className="overflow-hidden rounded-xl border border-[rgba(255,255,255,0.06)]">
              {TECH_STACK.map((item, i) => (
                <div
                  key={item.category}
                  className={`flex flex-col gap-1 p-4 sm:flex-row sm:items-center sm:gap-4 ${
                    i !== TECH_STACK.length - 1 ? "border-b border-[rgba(255,255,255,0.06)]" : ""
                  }`}
                >
                  <span className="w-32 shrink-0 text-sm font-semibold text-white">
                    {item.category}
                  </span>
                  <span className="text-sm text-zinc-400">{item.tech}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Build Timeline */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#131416" }}>
          <div className="mx-auto max-w-3xl px-6 md:px-8">
            <h2 className="mb-10 text-[28px] font-bold leading-[1.2] tracking-tight text-white md:text-[40px]">
              Build Process: Under 4 Weeks
            </h2>
            <div className="space-y-8">
              {TIMELINE.map((phase) => (
                <div key={phase.week} className="flex gap-4 md:gap-6">
                  <div className="flex flex-col items-center">
                    <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-brass-500 text-sm font-bold text-white">
                      {phase.week.replace("Week ", "")}
                    </div>
                    <div className="mt-2 w-0.5 grow bg-[rgba(255,255,255,0.06)]" />
                  </div>
                  <div className="pb-8">
                    <h3 className="mb-1 text-lg font-bold text-white">
                      {phase.title}
                    </h3>
                    <p className="mb-3 text-xs font-medium uppercase tracking-wider text-brass-300">
                      {phase.week}
                    </p>
                    <ul className="space-y-2">
                      {phase.items.map((item) => (
                        <li
                          key={item}
                          className="flex items-start gap-2 text-base leading-[1.6] text-zinc-400"
                        >
                          <svg
                            className="mt-1 h-4 w-4 shrink-0 text-brass-300"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="3"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <polyline points="20 6 9 17 4 12" />
                          </svg>
                          {item}
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Results & Key Takeaway */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#0E0F11" }}>
          <div className="mx-auto max-w-3xl px-6 text-center md:px-8">
            <h2 className="mb-6 text-[28px] font-bold leading-[1.2] tracking-tight text-white md:text-[40px]">
              Key Takeaway
            </h2>
            <p className="mx-auto max-w-2xl text-lg leading-[1.7] text-gray-300 md:text-xl">
              SellerPilotAI proves AI agents are production-ready today. What
              required 2-3 compliance team members now runs 24/7 at a fraction
              of the cost. This approach applies to any repetitive,
              knowledge-intensive task: sales prospecting, customer support,
              data analysis, content creation, operations management.
            </p>
          </div>
        </section>

        {/* CTA */}
        <section className="py-16 md:py-24" style={{ backgroundColor: "#131416" }}>
          <div className="mx-auto max-w-7xl px-6 md:px-8">
            <div className="mx-auto max-w-2xl rounded-2xl border border-blue-500/20 p-8 text-center shadow-lg md:p-12" style={{ backgroundColor: "#16181B" }}>
              <h2 className="mb-4 text-[28px] font-bold leading-[1.15] tracking-tight text-white md:text-[40px]">
                Want Us to Build Something Like This for You?
              </h2>
              <p className="mb-8 text-base leading-[1.6] text-zinc-400 md:text-lg">
                We build custom AI agents and SaaS products from concept to
                launch. Start with a free AI Readiness Audit.
              </p>
              <a
                href="/contact"
                className="btn-glow inline-block rounded-lg bg-gradient-to-r from-brass-500 to-bone-200 px-8 py-4 text-lg font-semibold text-white shadow-sm transition-all duration-150 hover:-translate-y-0.5 hover:shadow-md active:translate-y-0"
              >
                Book Your Free AI Audit
              </a>
              <p className="mt-4 text-sm text-zinc-500">
                Or visit{" "}
                <a
                  href="https://www.sellerpilotai.ai"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-medium text-brass-300 hover:underline"
                >
                  sellerpilotai.ai
                </a>{" "}
                to see the product live.
              </p>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
}
